
export  default {
    navList:[
        {
            'id':1,
            'title':'个人中心',
            'icon': 'fa fa-user-o',
            children:[
                {
                    'id':2,
                    'title':'个人资料',
                    'path':'profile',
                },
                {
                    'id':3,
                    'title':'修改密码',
                    'path':'profile-password'
                },
                {
                    'id':4,
                    'title':'我的权限',
                    'path':'profile-permissions',
                }
            ]
        },
        {
            'id':5,
            'title':'账户管理',
            'icon': 'fa fa-users',
            children:[
                {
                    'id':6,
                    'title':'用户列表',
                    'path':'users',
                },
                {
                    'id':7,
                    'title':'在线用户',
                    'path':'users-online',
                },
                {
                    'id':8,
                    'title':'锁定用户',
                    'path':'users-lock',
                }
            ]
        },
        {
            'id':9,
            'title':'权限管理',
            'icon': 'fa fa-unlock-alt',
            children:[
                {
                    'id':10,
                    'title':'角色列表',
                    'path':'roles',
                },
                {
                    'id':11,
                    'title':'权限列表',
                    'path':'permissions',
                },
            ]
        },
        {
            'id':12,
            'title':'日志管理',
            'icon': 'fa fa-bookmark',
            children:[
                {
                    'id':13,
                    'title':'操作日志',
                    'path':'logs',
                },
                {
                    'id':14,
                    'title':'登录日志',
                    'path':'logs-users',
                },
            ]
        },
        {
            'id':15,
            'title':'文章管理',
            'icon': 'fa fa-book',
            children:[
                {
                    'id':16,
                    'title':'写文章',
                    'path':'article-form',
                },
                {
                    'id':17,
                    'title':'文章列表',
                    'path':'article',
                },
                {
                    'id':18,
                    'title':'文章分类',
                    'path':'article-cate',
                },
            ]
        },
    ]
}